### ISSUE TITLE
Resource is not a Drawable (color or path)

### ISSUE THREAD

**Issue by MathSSDev** [tommybuonomo/morph-bottom-navigation#6]
Iam getting this error when launching activity:

    Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.constructNative(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at android.view.LayoutInflater.createView(LayoutInflater.java:597)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:699) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:495) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:400) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469) 
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
        at com.module.medyescore.Base.BaseActivity.onCreate(BaseActivity.kt:38) 
        at com.module.medyescore.Modules.Activities.MainActivity.onCreate(MainActivity.kt:71) 
        at android.app.Activity.performCreate(Activity.java:5242) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2164) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2249) 
        at android.app.ActivityThread.access$800(ActivityThread.java:141) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1212) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5113) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612) 
        at dalvik.system.NativeStart.main(Native Method) 
     Caused by: android.content.res.Resources$NotFoundException: Resource is not a Drawable (color or path): TypedValue{t=0x2/d=0x7f0400b8 a=5}
        at android.content.res.Resources.loadDrawable(Resources.java:2109)
        at android.content.res.Resources.loadDrawable(Resources.java:2062)
        at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
        at android.view.View.<init>(View.java:3558)
        at android.view.ViewGroup.<init>(ViewGroup.java:470)
        at android.widget.FrameLayout.<init>(FrameLayout.java:101)
        at com.google.android.material.bottomnavigation.BottomNavigationView.<init>(BottomNavigationView.java:118)
        at com.tbuonomo.morphbottomnavigation.MorphBottomNavigationView.<init>(MorphBottomNavigationView.kt:79)
        at com.tbuonomo.morphbottomnavigation.MorphBottomNavigationView.<init>(MorphBottomNavigationView.kt:75)
        at java.lang.reflect.Constructor.constructNative(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:597) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:699) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:495) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:400) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469) 
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
        at com.module.medyescore.Base.BaseActivity.onCreate(BaseActivity.kt:38) 
        at com.module.medyescore.Modules.Activities.MainActivity.onCreate(MainActivity.kt:71) 
        at android.app.Activity.performCreate(Activity.java:5242) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2164) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2249) 
        at android.app.ActivityThread.access$800(ActivityThread.java:141) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1212) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5113) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612) 
        at dalvik.system.NativeStart.main(Native Method) 

I copied the sample style and drawables. if more information is nedded i'll provide. Thanks!

**Comment by MathSSDev** [comment]
And if i do not set a style i get this: 

    2018-11-26 13:59:17.924 18092-18092/com.app.medyes E/AndroidRuntime: Caused by: java.lang.NoSuchMethodError: No direct method <init>(Lcom/google/android/material/shape/ShapePathModel;)V in class Lcom/google/android/material/shape/MaterialShapeDrawable; or its super classes (declaration of 'com.google.android.material.shape.MaterialShapeDrawable' appears in /data/app/com.app.medyes-cv1CAKvBi9mQ4zZUe765nw==/split_lib_dependencies_apk.apk)
        at com.tbuonomo.morphbottomnavigation.MorphBottomNavigationView.<init>(MorphBottomNavigationView.kt:109)
        at com.tbuonomo.morphbottomnavigation.MorphBottomNavigationView.<init>(MorphBottomNavigationView.kt:75)
