### ISSUE TITLE
Error inflating class com.tbuonomo.morphbottomnavigation.MorphBottomNavigationView

### ISSUE THREAD

**Issue by Ahsan221B** [tommybuonomo/morph-bottom-navigation#7]
This is my first time I'm using a Bottom Navigation View in my app. I did the following steps:
1. Added Dependedncy 
2. Copied com.tbuonomo.morphbottomnavigation.MorphBottomNavigationView in my XML
3. Copy pasted 2 styles created in the sample project
4. Added drawables

**Now when I run my app I get the following error:**
   `    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ahsanwrites.travearner/com.ahsanwrites.travearner.MainActivity}: android.view.InflateException: Binary XML file line #36: Binary XML file line #36: Error inflating class com.tbuonomo.morphbottomnavigation.MorphBottomNavigationView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2792)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2870)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1601)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:172)
        at android.app.ActivityThread.main(ActivityThread.java:6590)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: android.view.InflateException: Binary XML file line #36: Binary XML file line #36: Error inflating class com.tbuonomo.morphbottomnavigation.MorphBottomNavigationView
     Caused by: android.view.InflateException: Binary XML file line #36: Error inflating class com.tbuonomo.morphbottomnavigation.MorphBottomNavigationView
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
        at android.view.LayoutInflater.createView(LayoutInflater.java:647)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
        at com.ahsanwrites.travearner.MainActivity.onCreate(MainActivity.java:27)
        at android.app.Activity.performCreate(Activity.java:7023)
        at android.app.Activity.performCreate(Activity.java:7014)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1215)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2745)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2870)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1601)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:172)
        at android.app.ActivityThread.main(ActivityThread.java:6590)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 13: TypedValue{t=0x2/d=0x7f0400b0 a=4}
        at android.content.res.TypedArray.getDrawableForDensity(TypedArray.java:944)
        at android.content.res.TypedArray.getDrawable(TypedArray.java:928)
        at android.view.View.<init>(View.java:4768)
        at android.view.ViewGroup.<init>(ViewGroup.java:597)
        at android.widget.FrameLayout.<init>(FrameLayout.java:92)
        at android.widget.FrameLayout.<init>(FrameLayout.java:87)
        at com.google.android.material.bottomnavigation.BottomNavigationView.<init>(BottomNavigationView.java:118)
        at com.tbuonomo.morphbottomnavigation.MorphBottomNavigationView.<init>(MorphBottomNavigationView.kt:79)
        at com.tbuonomo.morphbottomnavigation.MorphBottomNavigationView.<init>(MorphBottomNavigationView.kt:75)
`

**Comment by Ahsan221B** [comment]
Also, at first I was getting an error similar to #2 so I migrated to AndroidX as you recommended so I hope it's not because of that.

**Comment by MathSSDev** [comment]
@Ahsan221B this error is caused by your App's style. In my case i was using Theme.AppCompat.Light.DarkActionBar and getting the same error but i changed to Theme.MaterialComponents.Light.DarkActionBar and works fine.

**Comment by MathSSDev** [comment]
Another error you'll find if your dependecies are up to date is an error like, NoSuchMethodError MaterialShapeDrawable.<init>. That's caused by multiple definitions of MaterialShapeDrawable, so you have the option to downgrade the dependencies or fork it and change library's dependencies.

**Comment by parane** [comment]
I also face same issue after migrate AndroidX. make sure  
 ```
  implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support:design:28.0.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    implementation 'com.android.support:support-vector-drawable:28.0.0'
```
are in old version

**Comment by winnerawan** [comment]
```
E/AndroidRuntime: Caused by: java.lang.NoSuchMethodError: 
No direct method <init>(Lcom/google/android/material/shape/ShapePathModel;)V 
in class Lcom/google/android/material/shape/MaterialShapeDrawable; 
or its super classes 
(declaration of 'com.google.android.material.shape.MaterialShapeDrawable'
```
i'm getting this issue, already in androidx and trying suggestion in here, but doesn't solve

**Comment by zohaib319** [comment]
E/AndroidRuntime: Caused by: java.lang.NoSuchMethodError: 
No direct method <init>(Lcom/google/android/material/shape/ShapePathModel;)V 
in class Lcom/google/android/material/shape/MaterialShapeDrawable; 
or its super classes 
(declaration of 'com.google.android.material.shape.MaterialShapeDrawable'


I'm also facing the same issue.
I have no idea what to do. It was working fine and then out of no where the crash started to happen. :(

**Comment by CamiloDelReal** [comment]
The error is in the use of MaterialComponents > 1.0.0 for creating MaterialShapeDrawable with a ShapePathModel
In MaterialComponents > 1.0.0 MaterialShapeDrawable dont have a constructor for ShapePathModel
see the changes in API at https://github.com/material-components/material-components-android/releases/tag/1.1.0-alpha01

for the moment, the best is downgrade MaterialComponents to 1.0.0 :(

**Comment by Duna** [comment]
Use

`implementation 'com.google.android.material:material:1.0.0-rc02'`

to avoid the issue

**Comment by VikashAnandJha** [comment]
> Theme.MaterialComponents.Light.DarkActionBar

Its Working  Thanks
